### ISSUE TITLE
Error running blockchain tests

### ISSUE THREAD

**Issue by gballet** [poanetwork/mana#402]
It seems that running the blockchain tests doesn't work, I get the following error:

```
~/src/mana/apps/blockchain % mix test test/blockchain_test.exs

  1) test runs blockchain tests (BlockchainTest)
     test/blockchain_test.exs:36
     ** (FunctionClauseError) no function clause matching in Enum.chunk_every/4

     The following arguments were given to Enum.chunk_every/4:

         # 1
         []

         # 2
         0

         # 3
         0

         # 4
         []

     Attempted function clauses (showing 1 out of 1):

         def chunk_every(enumerable, count, step, leftover) when is_integer(count) and count > 0 and is_integer(step) and step > 0

     code: grouped_test_per_fork()
     stacktrace:
       (elixir) lib/enum.ex:447: Enum.chunk_every/4
       test/blockchain_test.exs:45: anonymous fn/2 in BlockchainTest.grouped_test_per_fork/0
       (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
       test/blockchain_test.exs:44: BlockchainTest.grouped_test_per_fork/0
       test/blockchain_test.exs:37: (test)



Finished in 0.1 seconds
1 test, 1 failure

Randomized with seed 456979
```
It seems that this is because there are no tests (both `count` and `step` are 0); it's probably some instruction missing from the README or an issue with `bin/setup`.

**Comment by gballet** [comment]
My bad, I didn't use the `--recurse-submodules` option during the git sync.
